name: triqui
description: A simple Game Triqui.
publish_to: 'Triqui'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  lottie: ^1.4.1
  flutter_launcher_icons: ^0.10.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_native_splash:
  background_image: "assets/images/xobackground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/